#+OPTIONS: toc:nil

+ norang 님 설정 기반으로 모던하게 개선한 버전
+ [[https://www.youtube.com/watch?v=KZoQ4EkfDPo][Emacs Meet up Session II: Org Agenda - Vedang - YouTube]] 영상에 자세히 소개

* Org Mode Crate

This repository contains my configuration for Org Mode.

I've strived to make this configuration super simple to install and
use, if you face any problems please open an issue and let me know
about it.

** Caveats

 - This configuration is ONLY known to work with Emacs 27.2 and above.
   You are on your own with older versions of Emacs.

 - This configuration requires Org Mode 9.4 and above.

** Install

*** Manual Install
**** Get the code:
#+begin_src text
  $ git clone git://github.com/vedang/org-mode-crate.git /path/to/org-mode-crate
#+end_src

**** Add the following lines to your .emacs
#+begin_src emacs-lisp
  (add-to-list 'load-path "/path/to/org-mode-crate/")
  (setq org-directory "/path/to/org-files-dir")
  ;; Agenda does not have a key-binding by default.
  ;; Provide one as a starting point.
  (global-set-key (kbd "<f12>") 'org-agenda)
  (require 'org-mode-crate)
#+end_src

**** Press F12 to get started with your agenda

*** TODO Install via Melpa
*** TODO Install via El-Get
*** Install in DOOM emacs
#+begin_src emacs-lisp
;; in packages.el
(package! org-mode-crate
  :recipe (:host github :repo "vedang/org-mode-crate"))
;; in config.el
(use-package! org-mode-crate
             :init (global-set-key (kbd "<f12>") 'org-agenda)
             :config (require 'org-mode-crate))

#+end_src


*** TODO Install in Spacemacs emacs
[2023-12-05 Tue 08:57]


** Workflow notes

- Create and maintain as many files in your org-directory as you want.
- Currently, I don't handle recursively loading org files, so your
  org-directory should be a flat structure.
- Tasks are categorized as follows:
  + Important tasks: These tasks should be tagged with =important=.
  + Next tasks: In any given project, tag the next thing you want to
    do with the tag =next=. You can have many =next= tasks, but
    ideally you should have only one. Whenever a task goes into
    WORKING state, it automatically gets the =next= tag. Moving to any
    other state automatically removes this tag.
- The following hotkeys are provided for quick tagging:

- 조직 디렉터리에 원하는 만큼 파일을 만들고 관리하세요.
  - 현재 저는 재귀적으로 로드되는 조직 파일을 처리하지 않으므로 조직 디렉터리는
    평평한 구조여야 합니다.
  - 작업은 다음과 같이 분류됩니다:
    + 중요한 작업: 이러한 작업은 =중요=로 태그를 지정해야 합니다.
  + 다음 작업: 특정 프로젝트에서 다음에 하고 싶은 일에 =다음= 태그를 붙입니다.
    다음= 작업은 여러 개를 붙일 수 있지만, 이상적으로는 하나만 붙이는 것이
    좋습니다. 작업이 작업 중 상태가 되면 자동으로 =다음= 태그가 붙습니다. 다른
    상태로 이동하면 이 태그는 자동으로 제거됩니다.
- 빠른 태그 지정을 위해 다음 단축키가 제공됩니다:

#+begin_src emacs-lisp
  (setq org-tag-alist
        '(("next" . ?x)
          ("notes" . ?n)
          ("important" . ?i)
          ("action_items" . ?a)
          ("joy" . ?j)
          ("waiting" . ?w)))
#+end_src

** Optional notes

 - You can use the convenience function `bh/punch-in' (bound to =<f9> i=)
   to clock in a predetermined default task. All you need is the
   following one time setup:
   - Go to the org-task you want to use as the default task.
   - Give this task an org-id by running the function =org-id-get-create=
     #+begin_src emacs-lisp
       M-x org-id-get-create
     #+end_src
   - Copy the ID (stored in the task properties) and add the following
     line above =(require 'org-mode-crate)=
     #+begin_src emacs-lisp
       (defvar bh/organization-task-id "<task_id>")
     #+end_src
 - Now when you start org-mode, you can press =<f9> i= to clock in the
   default task.
